# Generated by Django 4.0.3 on 2022-05-10 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_remove_salesrecord_sales_rep'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='sales_rep',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sales_rep_record', to='sales_rest.salesrep'),
            preserve_default=False,
        ),
    ]
