# Generated by Django 4.0.3 on 2022-05-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_salesrecord_sales_rep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrep',
            name='employee_number',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
