# Generated by Django 4.0.3 on 2022-05-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0006_remove_automobilevo_color_remove_automobilevo_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='bought',
            field=models.BooleanField(default=False),
        ),
    ]
