# Generated by Django 4.0.3 on 2022-05-13 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0007_salesrecord_bought'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesrecord',
            name='bought',
        ),
    ]
