# Generated by Django 4.0.3 on 2022-05-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_remove_automobilevo_import_href'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='vin',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
