# Generated by Django 4.0.3 on 2022-05-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0006_alter_service_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
