# Generated by Django 4.0.3 on 2022-05-11 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0009_service_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='status',
            new_name='is_finished',
        ),
    ]
