# Generated by Django 4.0.3 on 2022-05-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0010_rename_status_service_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
